### ISSUE TITLE
Search Page UI Development

### ISSUE THREAD

**Issue by Goonco** [SilverCampus/client#2]
## **Description**

Search Page의 UI 개발

## **Todo**
<br>

> **1차 개발**

- [x] Section ⓐ [Search Section]
- [x] Section ⓑ [Topic Section]
- [ ] Section ⓒ [Personal Section]

<br>

> **2차 개발**

- [ ] Component 간격 맞추기
- [ ] Logo
- [ ] Button 배치
- [ ] 반응형

<br>

## **Etc**

Footer 제외 개발
공통컴포넌트들 고려해서 개발
반응형 고려 개발
